"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var point_1 = require("./point");
var post_1 = require("./post");
var like_component_1 = require("./like.component");
var point = new point_1.Point(1, 2);
point.draw();
var post = new post_1.Post(148);
post.LikeClicked();
post.LikeClicked();
post.LikeClicked();
post.LikeClicked();
post.LikeClicked();
var component = new like_component_1.LikeComponent(10, true);
component.onClick();
console.log('likesCount: ' + component.likesCount + ', isSelected: ' + component.isSelected);
component.onClick();
console.log('likesCount: ' + component.likesCount + ', isSelected: ' + component.isSelected);
component.onClick();
console.log('likesCount: ' + component.likesCount + ', isSelected: ' + component.isSelected);
